### ISSUE TITLE
True manual installation instructions missing

### ISSUE THREAD

**Issue by lbeltrame** [DocMarty84/koozic#13]
Since the installation script can't possibly support all distribution variants (like mine, openSUSE), it would be useful to have at least some rough instructions to do so manually (since the script I've seen does a lot of magic besides installing): some of us may not want to run Docker or do not want to download images from the registry.

**Comment by DocMarty84** [comment]
Hello,

Indeed, it's not easy to provide generic installation instructions. However, you can get some inspiration from the Docker file:

https://github.com/DocMarty84/koozic/blob/v1/extra/docker/Dockerfile

The main steps are:
- Install the Python dependencies and PostgreSql (steps # Install apt dependencies and # Install pip dependencies). You will need FFmpeg as well.
- Add a PostgreSql user corresponding to the user who will run KooZic, for example: su - postgres -c "createuser -s koozic"
- Launch with:

./odoo-bin --workers=4 --limit-time-cpu=1800 --limit-time-real=3600 --without-demo=all --no-database-list --log-level=warn

-------- Message d'origine --------

**Comment by DocMarty84** [comment]
Damn, all the formatting of my message was lost. I'll answer in a couple of days when I have access to a computer...

-------- Message d'origine --------

**Comment by DocMarty84** [comment]
Hello,

## Step 0: create a specific user

It is usually advised, for security reason, to always launch a service accessible from the outside world with a user different from `root`. Therefore, you should create for example the `koozic` user, with the appropriate access rights to your music files.

## Step 1: install prerequisites

First step of installation is to get all the Package and Pip dependencies. You can get the list here:
- https://github.com/DocMarty84/koozic/blob/daf0b70e972204fef89bb64e7b0858d9ddd62efa/extra/docker/Dockerfile#L25-L65
- https://github.com/DocMarty84/koozic/blob/daf0b70e972204fef89bb64e7b0858d9ddd62efa/extra/docker/Dockerfile#L72-L73

Depending on what is available for your distribution, some dependencies might need to be installed with Pip instead of your package manager. The complete list is given in the [requirements](https://github.com/DocMarty84/koozic/blob/v1/requirements.txt).

You will also need a recent version of FFmpeg (>= 3.4).

## Step 2: set-up PostgreSql

Second step is to set-up PostgreSql. Assuming you will run KooZic with the user named `koozic`, you need to create the corresponding PostgreSql user:
```bash
su - postgres -c "createuser -s koozic"
```

## Step 3: Download

Third step is to download the latest version of KooZic at https://github.com/DocMarty84/koozic/releases/latest (get the file `koozic-v1.1.0.tar.gz`), uncompress the archive.

## Step 4: launch KooZic

Fourth step is to execute this as the `koozic` user[1]:
```bash
./odoo-bin --workers=4 -d koozic-v1 --limit-time-cpu=1800 --limit-time-real=3600 --without-demo=all --no-database-list
```

After 10-20 seconds (the very first execution takes some time since it needs to create all database-related stuff), you should be able to connect to http://localhost:8069

So these are the minimum installation steps. The install script also creates a `systemd` daemon, and make use of a `~/.odoorc` file for setup. But these steps are not necessary.

[1] Technical note: on Fedora, you need to add `--db-template=template0` to the command line. This might be necessary for OpenSUSE as well.

**Comment by lbeltrame** [comment]
Something of the sort might work, thanks.

**Comment by DavidVentura** [comment]
This is how I set mine up in ansible

```
  tasks:
    - name: install koozic packages
      apt:
        name:
          - python3.5
          - python3-dev
          - python3-venv
          - python3-pip
          - ffmpeg
          - libldap2-dev
          - libsasl2-dev
          - libssl-dev
          - libtag1-dev
        state: present
        # FIXME UFW ALLOW 8069
    - name: create koozic user
      user:
        name: koozic
        system: no
        createhome: yes
        shell: "/bin/bash"
    - name: copy launcher file
      copy:
        src: ../host_files/koozic/start.sh
        dest: /home/koozic/start.sh
        owner: koozic
        mode: 0700

    - name: copy service files
      copy:
        src: ../host_files/koozic/koozic.service
        dest: /etc/systemd/system/
      notify: daemon-reload

    - name: ensure koozic service is enabled on boot
      systemd:
        name: "koozic"
        enabled: yes
        state: started
  handlers:
    - name: daemon-reload
      command: systemctl daemon-reload
````

Missing from here: manually download and untar the latest release, allow through firewall, write basic script that creates venv if missing, otherwise just uses it, run initial setup
